#384: Add `| teragrep exec foreachbatch` command that sets processing to batch mode
teragrep/pth_10 pull request #390
Opened 2024-10-24 08:32 UTC by eemhu

Adds `| teragrep exec foreachbatch` command, which turns off batch collect and sets processing to batch mode via step properties.

See issue
* #384

2024-10-24 09:52 UTC, 51-code requested changes
I guess this has to be tested in QA mostly as the unit tests don't support batches of data?

2024-10-24 09:52 UTC, 51-code commented on src/main/java/com/teragrep/pth10/steps/teragrep/TeragrepForEachBatchStep.java
> +public class TeragrepForEachBatchStep extends AbstractStep {
Class can be final.

2024-10-24 10:25 UTC, eemhu commented
> I guess this has to be tested in QA mostly as the unit tests don't support batches of data?

Yes, with the current testing setup it's not really possible. As-is the test only really tests that the command produces expected results data-wise, and with only one batch.

2024-10-28 11:04 UTC, 51-code approved these changes
LGTM now, I don't believe testing batches is possible in unit tests. There's an open issue #134 about that.

2024-10-30 13:51 UTC, kortemik approved these changes

2024-10-30 13:53 UTC, merged