updated schema assertions
teragrep/pth_10 pull request #456
Opened 2024-12-20 13:12 UTC by Abigael-JT

Updated assertions to use java objects for the following tests:
whereTest
TimechartStreamingTest
TableTransformationTest
XmlkvTransformationTest
FormatTransformationTest
StrcatTransformationTest

Related PRs:
* #447 
*  #429 

Related ticket:
* #65

2025-01-20 10:35 UTC, 51-code requested changes

2025-01-20 10:35 UTC, 51-code commented on src/test/java/com/teragrep/pth10/XmlkvTransformationTest.java
>      private final StructType testSchema = new StructType(new StructField[] {
Could this variable be moved to the test that utilizes it? It seems to be in use only in one test.

2025-01-20 11:51 UTC, Abigael-JT commented on src/test/java/com/teragrep/pth10/XmlkvTransformationTest.java
>      private final StructType testSchema = new StructType(new StructField[] {
that variable is also used here

@BeforeAll
    void setEnv() {
        this.streamingTestUtil = new StreamingTestUtil(this.testSchema);
        this.streamingTestUtil.setEnv();
    }
    
    
It might be a good idea to have a separate variable for that test

2025-01-20 11:56 UTC, 51-code commented on src/test/java/com/teragrep/pth10/XmlkvTransformationTest.java
>      private final StructType testSchema = new StructType(new StructField[] {
Oh, I had missed that. In that case I'd say which ever approach is fine. I'll approve the PR.

2025-01-20 11:57 UTC, 51-code approved these changes
LGTM

2025-01-21 08:41 UTC, kortemik approved these changes

2025-01-21 08:41 UTC, merged

2025-01-21 08:41 UTC, kortemik commented
Looks good! Merged!